################################################################################
# Contao 4.x Docker Development Container
# Apache 2,4, phpfpm, mysql@8.0
################################################################################
version: "3"
services:
    web:
        image: "webdevops/php-apache-dev:8.2"
        environment:
            DOCKER_DOMAIN: &hostname localhost
            PROJECT_NAME: &project contao-in-docker
            DEFAULT_PASSWORD: &password contao
            DOCROOT: web
            PHP_DISPLAY_ERRORS: 1
            PHP_MEMORY_LIMIT: "256M"
            PHP_MAX_EXECUTION_TIME: 30
            WEB_DOCUMENT_ROOT: "/app/web"
        ports:
            - "8080:80"
            - "9000:9000"
        volumes:
            - ./_www:/app
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: *password
            MYSQL_DATABASE: *project
            MYSQL_USER: *project
            MYSQL_PASSWORD: *password
        volumes:
            - ./_mysql:/var/lib/mysql
            # uncomment if you already had a dump, e.g. from backup
            # - ./import:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        ports:
            - 8090:8080
